### ISSUE TITLE
Clarify the VPC portion in acme-prod

### ISSUE THREAD

**Issue by sdot257** [antonbabenko/terragrunt-reference-architecture#3]
In `acme-prod/eu-central-1` is a folder to create the VPC. If I have two regions and in this example there's a `us-east-1` region, would I need to create a vpc folder w/ the same code in the `us-east-1` folder? if so, I thought terragrunt is supposed to allow you to have DRY code?

**Comment by antonbabenko** [comment]
Terragrunt indeed helps a lot with reducing duplication of the code, and the main differences which you need to provide are actual values for resources in different regions.

You are right, you will need to copy and update the content of `terragrunt.hcl` files.

PS: Consider using this - https://github.com/antonbabenko/modules.tf-demo - as a reference. It works with a recent version of Terragrunt and Terraform 0.12.
